Making all cards of equal length and resolving overflowing of circle image
Deveimer/vovoca-frontend pull request #45
Opened 2023-05-27 17:43 UTC by Anshika-Jain02

## Issue 12 resolved
*The height of various placards in the testimonial and team sections was not the same and it was giving the whole website a disoriented look and now it is looking fine.*

## Before :-
![vovoca 3](https://github.com/Deveimer/vovoca-frontend/assets/104912087/30b3851c-f3a7-4d8f-a02b-d2fc5300784e)
![vovoca](https://github.com/Deveimer/vovoca-frontend/assets/104912087/0eaed445-78ec-414e-b82c-99f5cd80bf8b)

## After:-
![vovoca_PR2](https://github.com/Deveimer/vovoca-frontend/assets/104912087/b344a5f4-1003-41fb-84d2-1eb0f1a1663c)
![vovoca_PR4](https://github.com/Deveimer/vovoca-frontend/assets/104912087/b49f4dc7-a099-4e3d-a34f-e7738de0d1c5)

*The circle image is overflowing out of its div and now, I have corrected this issue*
## Before :-
![vovoca 2](https://github.com/Deveimer/vovoca-frontend/assets/104912087/2eb01e6a-4717-4eb9-9aa7-cbfd5876788e)

## After:-
![vovoca_PR3](https://github.com/Deveimer/vovoca-frontend/assets/104912087/bf88b688-95f9-4c80-aac2-a5506eba2bfe)

**Thank you sir for giving me this opportunity**

2023-05-27 17:44 UTC, Anshika-Jain02 commented
@varun-singhh please review these changes.

2023-05-27 19:36 UTC, varun-singhh commented
@Anshika-Jain02 resolve merge conflicts

2023-05-27 20:21 UTC, Anshika-Jain02 commented
@varun-singhh sir, can you please guide me a little on how to resolve the merge conflict as I am new to this, and hence, I have no idea.

2023-05-28 06:24 UTC, varun-singhh commented
> @varun-singhh sir, can you please guide me a little on how to resolve the merge conflict as I am new to this, and hence, I have no idea.

take a pull from development branch and merge it to you branch `VOVOCA-12`

2023-05-28 06:26 UTC, varun-singhh requested changes

2023-05-28 06:26 UTC, varun-singhh commented on styles/Testimonial.module.css
>  .testimonial__img {
can you check for size in mobile view and attach the screen shot for the same

2023-05-28 11:01 UTC, Anshika-Jain02 commented
@varun-singhh please check whether the merge conflicts are resolved or not. Also, as the same class name "testimonial article" is used in all placards, changing its dimensions has affected some other containers like the contributors_article. so, I added this class to resolve the issue in all placards for big screen sizes.

You can check the size for this in mobile view by the below screenshot and #29 is taking care of its size in the mobile view accordingly.

![vovoca_changes_PR](https://github.com/Deveimer/vovoca-frontend/assets/104912087/77c784d2-0543-4145-8b74-f0a0362d998b)

2023-05-28 16:22 UTC, varun-singhh approved these changes

2023-05-28 16:22 UTC, merged

2023-06-02 18:33 UTC, Anshika-Jain02 commented
@varun-singhh please assign me appropriate level tag for this PR