grammatical and spelling errors were resolved
Deveimer/vovoca-frontend pull request #55
Opened 2023-05-28 06:53 UTC by HimanshuNarware

#Description 
Grammatical and spelling errors were resolved from the website successfully. It will improve the readability of the website as well as the user experience.

# issue code 
#5

#Screenshot
![62](https://github.com/Deveimer/vovoca-frontend/assets/83147410/c0416326-cd6e-466d-bf8b-4740715f8df7)

![63](https://github.com/Deveimer/vovoca-frontend/assets/83147410/b19e03ee-2df2-4967-893f-882ec8f99cae)

2023-05-28 07:06 UTC, kailashchoudhary11 commented
@HimanshuNarware Don't make a PR until the issue is assigned to you.

2023-05-28 16:11 UTC, varun-singhh requested changes

2023-05-28 16:11 UTC, varun-singhh commented on components/homepage/About/About.jsx
>                              </div>
Replace `Enjoy Royalty Free awesome music for free
                                We provide all of our services for free
                                Login and use vovoca for free forever`

with 

`Experience the rhythm, without spending a dime,
Unlock endless melodies, vovoca's free for a lifetime!`

2023-05-28 16:11 UTC, varun-singhh commented on components/homepage/About/About.jsx
>                          </div>
Replace `You don't even have to pay us or give us credit
                                for using our music anywhere, in your songs,
                                videos or an office presentation` 

with 

`Let the melodies soar, no strings attached,
Vovoca's music, freely used, without credit or cash.`

2023-05-28 16:11 UTC, varun-singhh commented on components/homepage/About/About.jsx
>                              </div>
Replace ` Login to utilize a complete set of features
                                of Vovoca. You can then easily filter
                                our music category wise` 

with 

`Unlock Vovoca's full potential with a single login,
Effortlessly browse and filter, music at your command`

2023-05-28 16:11 UTC, varun-singhh commented on components/homepage/About/About.jsx
>                              </div>
Replace `You can also share your work and talent with the whole
                                world for free. Sign in and upload your
                                created music with the world`

 with 

`Unleash your artistry, let your talent shine bright,
Share your creations with the world, day or night.
Vovoca welcomes your music, for free, with delight`

2023-05-28 16:11 UTC, varun-singhh commented on components/homepage/Footer/Footer.jsx
>              </p>
Replace with `Join forces with us, let's create something grand,
Collaboration awaits, reach out with a click at hand.
Share your ideas, let's shape our project, hand in hand.`

2023-05-28 16:11 UTC, varun-singhh commented on components/homepage/Header/Header.jsx
>            {authenticated === true ? (
Replace content in p tag with `Enter Vovoca's realm, where music knows no bounds,
Fuel your creativity with royalty-free sounds.
Unleash your imagination, let your creations astound`

2023-05-28 16:11 UTC, varun-singhh commented on pages/developers.js
>                        website, but BTS it was a roller coaster ride while
Replace content in p tag with `From humble beginnings to an extraordinary ride,
BTS, we conquered bugs and reached new heights.
Teamwork and dedication, our driving force with pride,
Hard work paid off, now Vovoca stands by your side.`

2023-05-28 16:11 UTC, varun-singhh commented on pages/privacy-policy.js
>                      </p>
Replace text with `Welcome to Vovoca, a remarkable endeavor by the passionate team at DevBucket. Our unwavering dedication has fueled the creation of this platform, offered to you completely free of charge. We owe our freedom today to the incredible open-source technologies that have seamlessly converged within Vovoca. With utmost commitment, our ultimate goal is to transform Vovoca into an open-source program, granting access to its inner workings once the foundation and interface are perfected. During our development journey, Vercel graciously hosts both our backend APIs and frontend, ensuring a seamless and efficient experience. Together, let's embrace the power of collaboration and embark on a harmonious musical voyage with Vovoca.`

2023-05-28 16:11 UTC, varun-singhh commented on pages/privacy-policy.js
>                      </p>
replace text with `At Vovoca, your privacy is our utmost priority. We understand the sensitivity of your personal information and have taken extensive measures to safeguard it. Through meticulous implementation of end-to-end encryption, we strive to ensure that your data remains protected throughout its journey. To provide an added layer of security, all passwords are securely hashed before being stored in our database. As an extra precaution, we strongly recommend refraining from using commonly used passwords on this platform. Instead, leverage the convenience of auto password generators available on various browsers. While Team DevBucket cannot provide an absolute guarantee against any potential data breaches or music leaks, we assure you that we have diligently adhered to industry best practices to fortify the security of your data. Rest assured, your privacy is in safe hands at Vovoca.`

2023-05-28 16:11 UTC, varun-singhh commented on pages/privacy-policy.js
>                      </p>
replace content with 

At Vovoca, we take the security of your data seriously and have implemented stringent measures to protect your information. Our web app is hosted using the highly secure and open-source programs, Vercel, Node, and PostgreSQL, ensuring a robust infrastructure for data storage. However, it is important to note that in the unlikely event of a data breach on the Vercel platform, there is a possibility of data leakage on our website.

While we strive to maintain the highest level of security, we cannot provide an absolute guarantee against data breaches. In the event of such an occurrence, neither Vovoca nor DevBucket can be held responsible. However, please be assured that we are working tirelessly, dedicating ourselves day and night to implementing additional methods and security measures to further enhance the protection of your music, email, and password within the Vovoca app.

We value your trust in us, and the privacy and security of your data remain our top priority. We will continue to make every effort to ensure the utmost security of your information and provide you with a safe and secure platform for your musical experience.

Thank you for choosing Vovoca, and we appreciate your understanding and support as we continually strive to improve our security practices.

2023-05-29 04:37 UTC, HimanshuNarware commented
> @HimanshuNarware Don't make a PR until the issue is assigned to you.

sorry sir

2023-05-29 07:55 UTC, closed without merging