Fixes reduntant onClick handling
Deveimer/vovoca-frontend pull request #60
Opened 2023-05-28 14:01 UTC by itshypon

Fixed #42 
Added both methods in one onClick handler, things seem to work fine.
Due to two onClick handlers and looking at precedence, only handler below is executed. Now, both of them works as both methods are added in one handler.
Still, give a check if something else is broken although everything seems fine.

2023-05-28 15:52 UTC, varun-singhh requested changes

2023-05-28 15:52 UTC, varun-singhh commented on components/Navbar/Navbar.jsx
> +              // onClick={() => logout()}
instead of commenting remove the dead code

2023-05-28 15:52 UTC, varun-singhh commented on components/Navbar/Navbar.jsx
> +              // onClick={onOpenModal}
remove dead code

2023-05-28 15:52 UTC, varun-singhh commented on components/Navbar/Navbar.jsx
>                &nbsp;
remove `{' '}`

2023-05-28 16:31 UTC, itshypon commented
Done @varun-singhh, mistakenly wrote same message for commit though.

2023-05-29 15:25 UTC, varun-singhh approved these changes

2023-05-29 15:25 UTC, merged