feature: add prettier formatting
Deveimer/vovoca-frontend pull request #70
Opened 2023-05-28 17:08 UTC by kailashchoudhary11

fixes #50

2023-05-28 17:31 UTC, varun-singhh requested changes

2023-05-28 17:31 UTC, varun-singhh commented on components/Dashboard/History.jsx
>    }
Still I can see single quote is not enabled, Please fix it.

2023-05-28 18:06 UTC, kailashchoudhary11 commented
@varun-singhh Done!

2023-05-29 12:44 UTC, kailashchoudhary11 commented
@varun-singhh  Please merge this so that I can work on linting.

2023-05-29 15:24 UTC, varun-singhh commented
@kailashchoudhary11 resolve conflicts

2023-05-29 15:35 UTC, kailashchoudhary11 commented
@varun-singhh Resolved. Merge it now else there will be conflicts again. 🥲

2023-05-29 17:40 UTC, varun-singhh approved these changes

2023-05-29 17:40 UTC, merged