Testimonial section updated
Deveimer/vovoca-frontend pull request #85
Opened 2023-05-29 20:41 UTC by Pragati-3003

I have updated the testimonial section .
![Screenshot 2023-05-30 020505](https://github.com/Deveimer/vovoca-frontend/assets/132778037/08f77fed-4787-4ee9-b546-0327aefc6e27)
Kindly inform me if you want any other changes.

2023-05-30 13:51 UTC, varun-singhh commented
@Pragati-3003 can you add a video/gif so that I can see how it looks.

2023-05-30 17:20 UTC, Pragati-3003 commented
> @Pragati-3003 can you add a video/gif so that I can see how it looks. also fix conflicting issues


https://github.com/Deveimer/vovoca-frontend/assets/132778037/e6a3b119-c6b1-441a-b7f6-7d44432272d9

If you wanna any other changes then please inform me.

2023-05-31 07:55 UTC, varun-singhh commented
@Pragati-3003 fix conflicting issue. Design looks good but We don't want transformation effect and hovering effect. It's just without any these just static design looks good. No need of adding hovering and transformation on this it has no use case.

2023-05-31 08:23 UTC, Pragati-3003 commented
> @Pragati-3003 fix conflicting issue. Design looks good but We don't want transformation effect and hovering effect. It's just without any these just static design looks good. No need of adding hovering and transformation on this it has no use case.

okie , I'll modify and solve merge conflicts.

2023-05-31 13:25 UTC, Pragati-3003 commented
> @Pragati-3003 fix conflicting issue. Design looks good but We don't want transformation effect and hovering effect. It's just without any these just static design looks good. No need of adding hovering and transformation on this it has no use case.

I have modified the section ad per your requirements, please review and merge it.

2023-06-03 18:06 UTC, kaustubhai commented
![image](https://github.com/Deveimer/vovoca-frontend/assets/47121025/fbaab7ab-0be5-4c56-a399-c5ee8c6abd01)

Still conflicting @Pragati-3003

2023-06-03 18:52 UTC, Pragati-3003 commented
> ![image](https://user-images.githubusercontent.com/47121025/243121133-fbaab7ab-0be5-4c56-a399-c5ee8c6abd01.png)
> 
> Still conflicting @Pragati-3003

Resolved all the conflicts ,please check once again.

2023-06-04 09:48 UTC, kaustubhai requested changes

2023-06-04 09:48 UTC, kaustubhai commented on package.json
Why am I seeing changes in package.json and package-lock?

2023-06-04 09:48 UTC, kaustubhai commented on styles/Testimonial.module.css
> +  /* box-shadow: rgba(0, 0, 0, 0.15) 0px 15px 25px, rgba(0, 0, 0, 0.05) 0px 5px 10px; */
remove the commented code

2023-06-04 09:48 UTC, kaustubhai commented on styles/Testimonial.module.css
> +.testimonial__content  p {
is this part of your change? you are altering the current code here? please update me with the impact

2023-06-04 17:37 UTC, Pragati-3003 commented on styles/Testimonial.module.css
> +  /* box-shadow: rgba(0, 0, 0, 0.15) 0px 15px 25px, rgba(0, 0, 0, 0.05) 0px 5px 10px; */
okie

2023-06-05 06:04 UTC, kaustubhai commented
@Pragati-3003 you deleted the package-lock completely. Do the following if you need help with your changes:
1. `git checkout Deveimer:Development`
2. `git pull origin Deveimer:Development`
3. `git checkout Pragati-3003:vovoca-14_2`
3. Go to [this](https://github.com/Deveimer/vovoca-frontend/pull/85/files) page, see only the changes that you want to make and copy paste them
4. Commit and Push
5. Create a new PR from that new branch.

Hope it helps, happy to help more

2023-06-05 07:35 UTC, Pragati-3003 commented
> @Pragati-3003 you deleted the package-lock completely. Do the following if you need help with your changes:
> 
> 1. `git checkout Deveimer:Development`
> 2. `git pull origin Deveimer:Development`
> 3. `git checkout Pragati-3003:vovoca-14_2`
> 4. Go to [this](https://github.com/Deveimer/vovoca-frontend/pull/85/files) page, see only the changes that you want to make and copy paste them
> 5. Commit and Push
> 6. Create a new PR from that new branch.
> 
> Hope it helps, happy to help more

Thanks for the explanation.
I have created a new pr #125

2023-06-27 03:22 UTC, closed without merging